    data:
      csv_path : 'Data/2d_cyl.csv'
      drop_hub : True
      constants:
        rho : 1.225 # kg/m^3
        mu : 1.78406e-05 # kg/m/s 
        mu_t : 41.60993336515875 # kg/m/s
        U_inf : 14 # m/s
        D : 178.3 # m 

    training:
      learning_rate : 0.0001
      num_epochs : 1000
      batch_size : -1
      test_size : 0.9
      fig_prefix : "simplenet"
      include_physics : True
      remove_dimensionality : True
      normaliser : [physics_normaliser, min_max_normaliser]
      shuffle : False
      network : simpleNet
      adaptive_loss_weights : True
      epochs_to_make_updates : 10
      start_adapting_at_epoch : 500
    