    data:
      csv_path : 'Data/2d_cyl.csv'
      drop_hub : True
      constants:
        rho : 1.225 # kg/m^3
        mu : 1.78406e-05 # kg/m/s 
        mu_t : 41.60993336515875 # kg/m/s
        U_inf : 14 # m/s
        D : 178.3 # m 
      seed : 42

    training:
      learning_rate : 0.0001
      num_epochs : 1000
      batch_size : -1 # -1 for full batch
      test_size : 0.9 # 0.9 for 90% test, 10% train
      include_physics : False
      # normaliser : [physics_normaliser, min_max_normaliser]
      # normaliser : [physics_normaliser, Z_normaliser]
      normaliser : [min_max_normaliser]
      # normaliser : [physics_normaliser]
      # normaliser : []
      shuffle : False
      network : simpleNet
      fig_prefix : "simpleNet"
      adaptive_loss_weights : False
      epochs_to_make_updates : 10
      start_adapting_at_epoch : 50
      finite_difference : False
    